# Generated by Django 3.2.5 on 2021-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('jobTitle', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=20000)),
                ('website', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
