# Generated by Django 3.2.5 on 2021-08-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
