# Generated by Django 3.2.5 on 2021-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210915_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ccInstituion',
        ),
        migrations.AddField(
            model_name='user',
            name='ccInstitution',
            field=models.CharField(default='', max_length=200),
        ),
    ]
