from django.db import models

class user(models.Model):
    latin = models.CharField(max_length=200, default='')
    hawaiian = models.CharField(max_length=200, default='')
    fName = models.CharField(max_length=200, default='')
    lName = models.CharField(max_length=200, default='')
    pronouns = models.CharField(max_length=200, default='')
    lsampAliance = models.CharField(max_length=200, default='')
    uInstitution = models.CharField(max_length=200, default='')
    uYear = models.CharField(max_length=200, default='')
    uMajor = models.CharField(max_length=200, default='')
    email = models.EmailField(max_length=200, default='')
    ccTransfer = models.CharField(max_length=200, default='')
    city = models.CharField(max_length=200, default='')
    state = models.CharField(max_length=200, default='')
    phone = models.CharField(max_length=200, default='')
    organization = models.CharField(max_length=200, default='')
    status = models.CharField(max_length=200, default='')
    title = models.CharField(max_length=200, default='')
    pInterest = models.CharField(max_length=200, default='')
    mentorship = models.CharField(max_length=200, default='')
    areaOfInterest = models.CharField(max_length=200, default='')
    areaOfExpertise = models.CharField(max_length=200, default='')
    pastResearch = models.CharField(max_length=200, default='')
    pastClubs = models.CharField(max_length=200, default='')
    linkedin = models.CharField(max_length=200, default='')
    twitter = models.CharField(max_length=200, default='')
    instagram = models.CharField(max_length=200, default='')
    website = models.CharField(max_length=200, default='')
    dateCreated = models.CharField(max_length=200, default='')
    createdBy = models.CharField(max_length=200, default='')
    ccTransfer2 =models.CharField(max_length=200, default='')
    ccInstitution = models.CharField(max_length=200, default='')
    address = models.CharField(max_length=200, default='')
    state2 = models.CharField(max_length=200, default='')
    bio = models.CharField(max_length=20000, default='')
    picture = models.ImageField()

    def __str__(self):
        return self.fName + " " + self.lName
